src/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// Routes are split into seperate files - get them here
foreach (File::allFiles(__DIR__ . '/routes') as $files) {

    require_once $files->getPathName();

}

src/app/models/CmsPage.php
<?php

// Composer
use Baum\Node;
use Watson\Validating\ValidatingTrait;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;
use Nicolaslopezj\Searchable\SearchableTrait;

class CmsPage extends Node implements SluggableInterface
{

    use ValidatingTrait;

    use SoftDeletingTrait;

    use SluggableTrait;

    use SearchableTrait;

    protected $fillable = [
        'title',
        'body',
        'redirect_url',
        'meta_description',
        'active',
        'nav_hidden',
        'parent_id'
    ];

    protected $sluggable = [
        'build_from' => 'title',
    ];

    protected $rules = [
        'parent_id' => ['integer'],
        'title' => ['required', 'max:255'],
        'body' => ['required', 'max:21844'],
        'active' => ['integer'],
        'nav_hidden' => ['integer'],
        'redirect_url' => ['max:255'],
        'meta_description' => ['max:255'],
    ];

    protected $searchable = [
        'columns' => [
            'title' => 10,
            'body' => 5,
        ],
    ];


    public function save(array $options = array())
    {
        // TODO! Wrap in exception handling to deal with nested set exceptions gracefully,
        // add a custom validation rule to use during validation, prune the list of
        // parents so invalid items are not presented
        return parent::save($options);
    }


    ///////////////////
    // Relationships //
    ///////////////////


    /**
     * Define polymorphic relationship with gallery photos (always sort by sequence)
     *
     * @return Collection
     */
    public function photos()
    {
        return $this->morphMany('GalleryPicture', 'imageable')->orderBy('sequence');
    }


    ////////////
    // Scopes //
    ////////////


    /**
     * Scope to limit results on public pages
     * @param Query $query
     * @return Query
     */
    public function scopeFrontendVisible($query)
    {
        return $query->whereActive(true)->whereNavHidden(false);
    }


    ///////////////
    // Accessors //
    ///////////////


    /**
     * Return the next level of categories
     *
     * @return Collection
     */
    public function getChildPagesAttribute()
    {
        return $this->getImmediateDescendants();
    }


    /**
     * Return the immediate parent category
     *
     * @return Category
     */
    public function getParentPageAttribute()
    {
        return $this->getParent();
    }


    /**
     * Get first gallery image, or an empty placeholder
     *
     * @return GalleryPicture
     */
    public function getPrimaryPhotoAttribute()
    {
        if (! $this->photos->isEmpty()) {
            return $this->photos->first();
        } else {
            return new GalleryPicture;
        }
    }
    

    //////////////
    // Mutators //
    //////////////


    /**
     * Save any 0 or otherwise non integer vals as null to avoid nested set issues
     */
    public function setParentIdAttribute($value)
    {
        $value = intval($value) === 0 ? null : $value;
        $this->attributes['parent_id'] = $value;
    }
}

src/app/models/Offer.php
<?php

// Core
use Carbon\Carbon;

class Offer extends Eloquent
{

    use SoftDeletingTrait;

    protected $fillable = ['offer_price', 'acceptance_status'];

    protected $dates = ['expires_at'];

    // Special case - keep the rules in a static to allow access externally
    // without instantiating the class, populate $this->rules from constructor
    public static $static_rules = ['offer_price' => ['required', 'numeric']];
    protected $rules = [];

    // Def class constants and a container to reference the acceptance status
    const OFFER_PENDING = 00;
    const OFFER_DECLINED = 10;
    const OFFER_DECLINED_AUTO = 11;
    const OFFER_ACCEPTED = 20;
    const OFFER_SELLER_CANCELLED = 30;
    public static $acceptance_statuses = [
        self::OFFER_PENDING => 'Pending',
        self::OFFER_DECLINED => 'Declined',
        self::OFFER_DECLINED_AUTO => 'Declined',
        self::OFFER_ACCEPTED => 'Accepted',
        self::OFFER_SELLER_CANCELLED => 'Cancelled by seller',
    ];

    ///////////////
    // Bootstrap //
    ///////////////


    public function __construct()
    {
        parent::__construct();

        // Set up rules
        $this->rules = self::$static_rules;
    }


    /**
     * Boot the parent, register observer
     */
    public static function boot()
    {
        parent::boot();

        Offer::observe(new OfferObserver);
    }


    ///////////////////
    // Relationships //
    ///////////////////


    /**
     * BelongsTo relationship with source advert
     *
     * @return Advert
     */
    public function advert()
    {
        return $this->belongsTo('Advert');
    }


    /**
     * BelongsTo relationship with potentially buying user
     *
     * @return User
     */
    public function initiator()
    {
        return $this->belongsTo('User', 'initiator_id');
    }


    ///////////////
    // Accessors //
    ///////////////


    /**
     * Virtual property for display of offer acceptance status
     *
     * @return string
     */
    public function getAcceptanceStatusStringAttribute()
    {
        return self::$acceptance_statuses[$this->acceptance_status];
    }


    /**
     * Get a GBP formatted currency string for the offer price
     *
     * @return String
     */
    public function getGbpOfferPriceStringAttribute()
    {
        return Converter::to('currency.gbp')->value($this->offer_price)->format();
    }


    ////////////
    // Scopes //
    ////////////


    /**
     * Limit query to only pending (not expired, declined or auto declined).
     * NOTE: extra where closure for query grouping
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopePending($query)
    {
        return $query->where(function($query) {
            $query->where('expires_at', '>=', Carbon::now())
            ->where('acceptance_status', '=', self::OFFER_PENDING);
        });
    }


    /**
     * Limit query to only accepted offers with outstanding payment
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopePaymentRequired($query)
    {
        return $query->where(function($query) {
            $query->where('acceptance_status', '=', self::OFFER_ACCEPTED)
            ->whereHas('advert', function($query) {
                $query->whereNull('purchased_at');
            });
        });
    }


    /**
     * Limit query to only accepted offers which have been paid for
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopePaymentComplete($query)
    {
        return $query->where(function($query) {
            $query->where('acceptance_status', '=', self::OFFER_ACCEPTED)
            ->whereHas('advert', function($query) {
                $query->whereNotNull('purchased_at');
            });
        });
    }


    /**
     * Limit query to only actioned (expired or not on pending status)
     * NOTE: extra where closure for query grouping
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopeActioned($query)
    {
        return $query->where(function($query) {
            $query->where('expires_at', '<', Carbon::now())
            ->orWhere('acceptance_status', '!=', self::OFFER_PENDING);
        });
    }


    /**
     * Scope to limit results for use in Ajax partials
     *
     * @param Query $query
     * @return Query
     */
    public function scopeForAjax($query)
    {
        return $query->orderBy('created_at', 'DESC')->limit(10);
    }
}

src/app/models/User.php
<?php

use Zizaco\Confide\ConfideUser;
use Zizaco\Confide\ConfideUserInterface;
use Zizaco\Entrust\HasRole;
use Cmgmyr\Messenger\Traits\Messagable;


class User extends Eloquent implements ConfideUserInterface
{
    use ConfideUser;
    use HasRole;
    use Messagable;


    ///////////////////
    // Relationships //
    ///////////////////


    /**
     * Define relationship to Profile
     *
     * @return  Profile
     */
    public function profile()
    {
        return $this->hasOne('Profile');
    }


    /**
     * Define relationship with any advert purchases
     *
     * @return Collection
     */
    public function transactions()
    {
        return $this->hasMany('Transaction', 'buyer_id');
    }


    /**
     * Define relationship with any advert offers made
     *
     * @return Collection
     */
    public function offersMade()
    {
        return $this->hasMany('Offer', 'initiator_id')->orderBy('created_at', 'desc');
    }


    /**
     * Define relationship with any offers received
     *
     * @return Colection
     */
    public function offersReceived()
    {
        return $this->hasManyThrough('Offer', 'Advert')->orderBy('created_at', 'desc');
    }


    /**
     * Define relationship with any activities
     *
     * @return Collection
     */
    public function activities()
    {
        return $this->hasMany('Activity')->orderBy('created_at', 'desc');
    }


    ///////////////
    // Accessors //
    ///////////////


    /**
     * Add virtual property to query whether Profile completed
     *
     * @return  Boolean
     */
    public function getIsProfileHolderAttribute()
    {
        // Check existence of dynamic profile property defined above
        return $this->profile ? true : false;
    }


    /**
     * Add virtual property to query whether Profile has a PayPal ID assigned
     *
     * @return  Boolean
     */
    public function getIsExtendedProfileHolderAttribute()
    {
        // Check existence of dynamic profile property defined above, and whether
        // the user has set their PayPal ID in it
        return $this->profile && $this->profile->paypal_id ? true : false;
    }


    /**
     * Add virtual property for listing user type
     *
     * @return  String
     */
    public function getRolesListAttribute()
    {
        $roles_list = $this->roles()->getResults()->lists('name');
        return $roles_list ? implode(', ', $roles_list) : 'Deactivated';
    }


    /**
     * Add a virtual property to see if any new activities or messages exist
     *
     * @return boolean
     */
    public function hasNewActivities()
    {
        if ($this->newMessagesCount() || $this->activities()->unread()->count()) {
            return true;
        } else {
            return false;
        }
    }


    //////////////
    // Mutators //
    //////////////


    /**
     * Set base user role to (exactly) one of the predefined types
     *
     * @param   String $role
     * @return  void
     */
    public function setBaseRole($required_role)
    {
        // Remove all base role
        foreach (Role::$base_roles as $base_role) {
            $role = Role::where('Name', '=', $base_role)->first();
            $this->detachRole($role);
        }

        // Attach the required role
        $role = Role::where('Name', '=', $required_role)->first();
        $this->attachRole($role);
    }


    //////////
    // Misc //
    //////////


    /**
     * Deactivate account (remove all roles)
     *
     * @return void
     */
    public function deactivate()
    {
        $this->roles()->sync([]);
    }
}

src/app/controllers/Admin/MembersController.php
<?php

namespace Admin;

// Domain
use User;
use Role;

// Core
use Input;
use Redirect;
use View;

// Third Party
use Notification;

class MembersController extends \BaseController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $users = User::all();
        return View::make('admin.members.index', compact('users'));
    }


    /**
     * Make admin
     *
     * @param  User   $user
     * @return Response
     */
    public function promote(User $user)
    {
        $user->setBaseRole(Role::ROLE_ADMIN);
        Notification::success('Role changed');
        return Redirect::route('admin.members.index');
    }


    /**
     * Make standard member
     *
     * @param  User   $user
     * @return Response
     */
    public function demote(User $user)
    {
        $user->setBaseRole(Role::ROLE_MEMBER);
        Notification::success('Role changed');
        return Redirect::route('admin.members.index');
    }


    /**
     * Deactivate (remove all base roles)
     *
     * @param  User   $user
     * @return Response
     */
    public function deactivate(User $user)
    {
        $user->deactivate();
        Notification::success('User deactivated');
        return Redirect::route('admin.members.index');
    }
}

src/app/controllers/Member/ActivitiesController.php
<?php

namespace Member;

// Domain
use Activity;
use Role;

// Core
use Input;
use Redirect;
use View;
use Response;

// Third Party
use Notification;
use Confide;

class ActivitiesController extends \BaseController
{

    /**
     * Display a listing of the resource.
     * GET /tags
     *
     * @return Response
     */
    public function index()
    {
        $activities = Confide::user()->activities;
        return View::make('member.alerts', compact('activities'));
    }



    /**
     * Mark as read - called via ajax
     *
     * @param  Activity $activity
     * @return Response
     */
    public function markRead(Activity $activity)
    {
        $activity->read = true;
        $activity->save();
        return Response::json('Marked as read', 200);
    }


    /**
     * Update the resource (simply toggle read/unread status)
     *
     * @param  Activity $activity
     * @return Response
     */
    public function update(Activity $activity)
    {
        $activity->read = $activity->read ? false : true;
        $activity->save();
        Notification::success('Activity read status toggled!');
        return Redirect::route('member.alerts.index');
    }


    /**
     * Update all resources for this role (simply mark them as read)
     *
     * @return Response
     */
    public function updateAll()
    {
        Confide::user()->activities()->update(['read' => true]);
        Notification::success('Marked all activities as read!');
        return Redirect::route('member.alerts.index');
    }


    /**
     * Delete the resource
     *
     * @param  Activity $activity
     * @return Response
     */
    public function destroy(Activity $activity)
    {
        $activity->delete();
        Notification::success('Activity deleted!');
        return Redirect::route('member.alerts.index');
    }


    /**
     * Delete all resources for this user
     *
     * @return Response
     */
    public function destroyAll()
    {
        Confide::user()->activities()->delete();
        Notification::success('All activities deleted');
        return Redirect::route('member.alerts.index');
    }
}

src/app/controllers/Member/ProfileController.php
<?php

namespace Member;

use Profile;

use Confide;
use Notification;

use Input;
use Redirect;
use View;
use URL;

class ProfileController extends \BaseController
{

    /**
     * Show profile edit form
     *
     * @return  Profile
     */
    public function manage()
    {
        $user = Confide::user();
        $profile = Profile::firstOrNew(['user_id' => $user->id]);
        $rules = $profile->getRules();
        return View::make('member.manage-profile', compact('profile', 'rules'));
    }


    /**
     * Process an edit form submission
     */
    public function doManage()
    {
        $user = Confide::user();
        $profile = Profile::firstOrNew(['user_id' => $user->id]);
        if ($profile->fill(Input::except('user_id'))->save()) {
            Notification::success('Your profile has been saved');
            return Redirect::intended(URL::route('member.dashboard'));
        } else {
            return Redirect::back()->withErrors($profile->getErrors())->withInput();
        }
    }


    /**
     * Show change password form
     */
    public function password()
    {
        return View::make('member.update-password');
    }


    /**
     * Process change password form submission
     */
    public function doPassword()
    {
        $repo = \App::make('UserRepository');
        if ($repo->changePassword(Confide::user(), Input::all()) === true) {
            Notification::success('Your password has been changed');
            return Redirect::route('member.dashboard');
        } else {
            Notification::error('Could not update your password, please try again');
            return Redirect::back();
        }
    }
}

src/app/views/member/dashboard/index.blade.php
@extends('member.layout')

@section('title', 'Dashboard')

@section('content')

<div class="row">

	<div class="col-md-12 col-lg-12">

		@if (Confide::user()->is_profile_holder)

			<section id="dashboard-header">
				<div>
					<h1>Dashboard</h1>
				</div>
			</section>

			{{-- Buying --}}
			<section class="member-dashboard-boxout">

				<div class="member-dashboard-boxout-lhs">

					<h2>Buying</h2>
					
					<p><a href="{{ route('member.offers.payment-required') }}"
					class="member-dashboard-load-partial member-dashboard-load-partial-auto" 
					data-target-div="buying-target-div">Purchases awaiting payment</a></p>
				
					<p><a href="{{ route('member.offers.purchase-history') }}"
					class="member-dashboard-load-partial" 
					data-target-div="buying-target-div">Recent purchases</a></p>

					<p>{{ link_to_route('member.offers.purchases', 'View all my purchases') }}
						<span class="glyphicon glyphicon-new-window"> </span>
					</p>

				</div>

				<div class="member-dashboard-boxout-rhs" id="buying-target-div"></div>

			</section>

			{{-- Selling --}}
			<section class="member-dashboard-boxout">

				@if (! Confide::user()->is_extended_profile_holder)

				{{-- Not eligeable to sell, show error --}}
					<div class="member-dashboard-boxout-lhs">
						<h2>Selling</h2>
					</div>

					<div class="member-dashboard-boxout-rhs" id="selling-target-div">
						<p class="h2 text-warning text-center">You will not be able to sell until you 
						{{ link_to_route('member.profile.manage', 'add a PayPal ID to your user profile',
							null, ['class' => 'alert-link']) }}.</p>
					</div>

				@else

				{{-- Is extended profile holder, render data --}}
					<div class="member-dashboard-boxout-lhs">

							<h2>Selling</h2>


							<p><a href="{{ route('member.listings.all-active') }}"
							class="member-dashboard-load-partial member-dashboard-load-partial-auto" 
							data-target-div="selling-target-div">Currently selling</a></p>
							
							<p><a href="{{ route('member.listings.recently-sold') }}"
							class="member-dashboard-load-partial" 
							data-target-div="selling-target-div">Recently completed sales</a></p>

							<p>{{ link_to_route('member.listings.create', 'Add a new listing') }} 
								<span class="glyphicon glyphicon-new-window"> </span>
							</p>
							<p>{{ link_to_route('member.listings.index', 'View all my sales') }}
								<span class="glyphicon glyphicon-new-window"> </span>
							</p>

					</div>

					<div class="member-dashboard-boxout-rhs" id="selling-target-div"></div>
				@endif
			</section>

			{{-- Offers --}}
			<section class="member-dashboard-boxout">

				<div class="member-dashboard-boxout-lhs">

					<h2>Offers</h2>

					<p><a href="{{ route('member.offers.actioned') }}"
					class="member-dashboard-load-partial member-dashboard-load-partial-auto"
					data-target-div="offer-target-div">Accepted or declined by seller</a></p>

					<p><a href="{{ route('member.offers.awaiting_response') }}"
					class="member-dashboard-load-partial"
					data-target-div="offer-target-div">Awaiting a response from seller</a></p>

					<p>{{ link_to_route('member.offers.index', 'View all my offers') }}
						<span class="glyphicon glyphicon-new-window"> </span>
					</p>

				</div>

				<div class="member-dashboard-boxout-rhs" id="offer-target-div"></div>

			</section>

		@else

			<div class="jumbotron">
				<h1>Welcome!</h1>
				<p>Now that you have signed up you should create your profile.
				You will need to do this before you can submit a listing or complete
				a purchase.</p>
				<p>
					<a class="btn btn-primary btn-lg"
					href="{{ route('member.profile.manage') }}"
					role="button">Create my profile</a>
				</p>
			</div>

			<div class="jumbotron">
				<h2>Don't want to create a profile just yet?</h1>
				<p>No problem. If you just want to browse, 
				{{ link_to_route('buying_home', 'visit the buying homepage') }}
				and see what's available.</p>
			</div>

		@endif

	</div>

</div>

@stop

src/app/views/member/dashboard/no-data.blade.php
<p class="h2 text-warning text-center">No data to display</p>

src/app/views/member/dashboard/selling-item.blade.php
<div class="row">

	<a href="{{ route('member.listings.summary', ['id' => $advert->id]) }}">
		<div class="col-xs-3">
			<img src="{{ $advert->primary_photo->image->url('thumb') }}" class="thumbnail">
		</div>
		<div class="col-xs-9">

			<p>{{ $advert->manufacturer->name }} {{ $advert->title }}, <b>{{ $advert->gbp_price_string }}</b>
			<?php $bs3_class = $advert->approval_status == Advert::ADVERT_APPROVED ? 'success' : 'warning' ?>
			<span class="label label-{{ $bs3_class }}">{{ $advert->approval_status_string }}</span></p>

			@if ($advert->winning_offer)
				
				<p>Sold for {{ $advert->winning_offer->gbp_offer_price_string }}

					@if($advert->purchase_status === Advert::ADVERT_RESERVED)
						<span class="label label-warning">{{ $advert->purchase_status_string }}</span>
					@elseif ($advert->purchase_status === Advert::ADVERT_PURCHASED || $advert->purchase_status === Advert::ADVERT_SHIPPED)
						<span class="label label-success">{{ $advert->purchase_status_string }}</span>
					@endif

				</p>

			@else

				<p>{{ $advert->offers()->count() }} offers</p>

			@endif

		</div>
	</a>

</div>