src/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// Routes are split into seperate files - get them here
foreach (File::allFiles(__DIR__ . '/routes') as $files) {

    require_once $files->getPathName();

}

src/app/models/Advert.php
<?php

// Core
use Carbon\Carbon;
use Illuminate\Support\Collection;
// Composer
use Watson\Validating\ValidatingTrait;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;
use Nicolaslopezj\Searchable\SearchableTrait;

class Advert extends Eloquent implements SluggableInterface
{
    // Consts to use when building searchfilters
    const SFKEY_PRICE = 'searchfilter_advert_prices_';
    const SFKEY_SORT = 'searchfilter_advert_sort';

    use SoftDeletingTrait;

    use ValidatingTrait;

    use SluggableTrait;

    use SearchableTrait;

    protected $fillable = [
        'approval_status', 'title', 'body', 'price', 'min_offer_price',
        'category_id', 'manufacturer_id', 'mfr_other_freetext',
        'purchased_at', 'reserved_at', 'shipped_at',
    ];

    protected $dates = ['purchased_at', 'reserved_at', 'shipped_at'];

    protected $sluggable = [
        'build_from' => 'title',
    ];

    protected $searchable = [
        'columns' => [
            'title' => 10,
            'body' => 5,
            'manufacturers.name' => 8,
            'mfr_other_freetext' => 8,
        ],
        'joins' => [
            'manufacturers' => ['adverts.manufacturer_id', 'manufacturers.id'],
        ],
    ];

    protected $rules; // Rules will be set in the constructor in this model

    protected $cachedDirty = []; // Used to cache the result of isDirty()

    // Def class constants and a container to reference the approval status
    const ADVERT_PENDING = 0;
    const ADVERT_DECLINED_TEMP = 1;
    const ADVERT_DECLINED_PERM = 2;
    const ADVERT_APPROVED = 3;
    const ADVERT_DRAFT = 4;
    public static $approval_statuses = [
        self::ADVERT_DRAFT => 'Draft',
        self::ADVERT_PENDING => 'Pending',
        self::ADVERT_DECLINED_TEMP => 'Declined - needs to be amended',
        self::ADVERT_DECLINED_PERM => 'Declined - rejected, needs deletion',
        self::ADVERT_APPROVED => 'Approved',
    ];

    // Def class constants and a container to reference the purchase status
    const ADVERT_PURCHASED = 0;
    const ADVERT_AVAILABLE = 1;
    const ADVERT_RESERVED = 2;
    const ADVERT_SHIPPED = 3;
    public static $purchase_statuses = [
        self::ADVERT_PURCHASED => 'Purchased',
        self::ADVERT_AVAILABLE => 'Available',
        self::ADVERT_RESERVED => 'Reserved',
        self::ADVERT_SHIPPED => 'Shipped',
    ];

    // Def sort labels
    public static $sort = [
        ['label' => 'Date added, oldest first', 'col' => 'created_at', 'dir' => 'asc'],
        ['label' => 'Data added, newest first', 'col' => 'created_at', 'dir' => 'desc'],
        ['label' => 'Price, lowest first', 'col' => 'price', 'dir' => 'asc'],
        ['label' => 'Price, highest first', 'col' => 'price', 'dir' => 'desc'],
        ['label' => 'Title', 'col' => 'title', 'dir' => 'asc'],
    ];

    ///////////////
    // Bootstrap //
    ///////////////

    /**
     * Set this model's rules on instantiation (requires logic and external values).
     */
    public function __construct()
    {
        parent::__construct();

        // Get config and processed values to use in rules
        $min_price = Config::get('domain.advert.min_price', 1);
        $max_price = Config::get('domain.advert.max_price', 99999.99);
        $min_offer_price_percentage = Config::get('domain.advert.min_offer_price_percentage', 50);
        $valid_approval_statuses_string = implode(',', array_keys(self::$approval_statuses));
        $advert_container_categories_string = implode(
            ',',
            Category::isAdvertContainer()->get()->lists('id')
        );

        $this->rules = [
            'approval_status' => ["in:{$valid_approval_statuses_string}"],
            'title' => ['required', 'max:255'],
            'body' => ['required', 'max:16383'],
            'active' => ['integer'],
            'price' => ['required', 'numeric', "between:{$min_price},{$max_price}"],
            'min_offer_price' => [
                'sometimes',
                'numeric',
                "is_percentage_of:price,{$min_offer_price_percentage},100",
            ],
            'category_id' => ['required', "in:{$advert_container_categories_string}"],
            'manufacturer_id' => ['required', 'exists:manufacturers,id'],
            'mfr_other_freetext' => ['max:255'],
        ];
    }

    /**
     * Boot the parent, register observer.
     */
    public static function boot()
    {
        parent::boot();

        self::observe(new AdvertObserver());
    }

    ///////////////////
    // Relationships //
    ///////////////////

    /**
     * Define belongsTo relationship with owner user.
     *
     * @return User
     */
    public function owner()
    {
        return $this->belongsTo('User', 'user_id');
    }

    /**
     * Define belongsTo relations with containing category.
     *
     * @return Category
     */
    public function category()
    {
        return $this->belongsTo('Category')->withTrashed();
    }

    /**
     * Define belongsTo relationship with manufacturer.
     *
     * @return Manufacturer
     */
    public function manufacturer()
    {
        return $this->belongsTo('Manufacturer')->withTrashed();
    }

    /**
     * Define hasMany relationship with transactions.
     *
     * @return Collection
     */
    public function transactions()
    {
        return $this->hasMany('Transaction');
    }

    /**
     * Define hasMany relationship with offers.
     *
     * @return Collection
     */
    public function offers()
    {
        return $this->hasMany('Offer')->orderBy('id', 'desc');
    }

    /**
     * Define polymorphic relationship with gallery photos (always sort by sequence).
     *
     * @return Collection
     */
    public function photos()
    {
        return $this->morphMany('GalleryPicture', 'imageable')->orderBy('sequence');
    }

    /**
     * Define hasmany relationship with postage options.
     *
     * @return Collection
     */
    public function postage()
    {
        return $this->hasMany('PostageOption')->orderBy('region_name');
    }

    ///////////////
    // Accessors //
    ///////////////

    /**
     * Ensure approval status is returned as an int (PHP MySQL driver issues).
     *
     * @return int
     */
    public function getApprovalStatusAttribute()
    {
        return (integer) $this->attributes['approval_status'];
    }

    /**
     * Virtual property for display of advert approval status.
     *
     * @return string
     */
    public function getApprovalStatusStringAttribute()
    {
        return self::$approval_statuses[$this->approval_status];
    }

    /**
     * Virtual property for calculating advert purchase status.
     *
     * @return int
     */
    public function getPurchaseStatusAttribute()
    {
        if ($this->shipped_at) {
            return self::ADVERT_SHIPPED;
        } elseif ($this->purchased_at) {
            return self::ADVERT_PURCHASED;
        } elseif ($this->reserved_at) {
            return self::ADVERT_RESERVED;
        } else {
            return self::ADVERT_AVAILABLE;
        }
    }

    /**
     * Virtual property for displaying advert an purchase status string.
     *
     * @return string
     */
    public function getPurchaseStatusStringAttribute()
    {
        return self::$purchase_statuses[$this->purchase_status];
    }

    /**
     * Check whether there is currently an active transaction for this advert.
     *
     * @return bool
     */
    public function getPurchaseInProgressAttribute()
    {
        $transactions = $this->transactions()->
            where('expires_at', '>=', Carbon::now())->
            where('paypal_status', '=', Transaction::PP_TRANS_CREATED)
            ->get();

        return $transactions->isEmpty() ? false : true;
    }

    /**
     * Return the winning offer, or boolean false if there isn't one.
     *
     * @return Offer
     */
    public function getWinningOfferAttribute()
    {
        $offer = $this->offers()
            ->where('acceptance_status', '=', Offer::OFFER_ACCEPTED)
            ->first();

        return $offer ?: false;
    }

    /**
     * Return the transaction which has a COMPLETED status, or false if there isn't one.
     *
     * @return Transaction
     */
    public function getWinningTransactionAttribute()
    {
        $transaction = $this->transactions()
            ->where('paypal_status', '=', Transaction::PP_TRANS_COMPLETE)
            ->first();

        return $transaction ?: false;
    }

    /**
     * Get first gallery image, or an empty placeholder.
     *
     * @return GalleryPicture
     */
    public function getPrimaryPhotoAttribute()
    {
        if (!$this->photos->isEmpty()) {
            return $this->photos->first();
        } else {
            return new GalleryPicture();
        }
    }

    /**
     * Get the name of the manufacturer, either via a relation or freetext (for 'other').
     *
     * @return string
     */
    public function getManufacturerNameStringAttribute()
    {
        return $this->manufacturer->name == 'Other'
            ? $this->mfr_other_freetext
            : $this->manufacturer->name;
    }

    /**
     * Get a location string for the advert.
     *
     * @return string
     */
    public function getLocationStringAttribute()
    {
        // Retrieve owner's city and country, filtering blank vals
        $location_parts = array_where([
            $this->owner->profile->city,
            $this->owner->profile->telephone_country,
        ], function ($key, $value) {
            return !empty($value);
        });

        // Return joined location elements, or placeholder if none found
        return $location_parts ? implode(', ', $location_parts) : 'Location unknown';
    }

    /**
     * Get a GBP formatted currency string for the price.
     *
     * @return string
     */
    public function getGbpPriceStringAttribute()
    {

src/app/models/Offer.php
<?php

// Core
use Carbon\Carbon;

class Offer extends Eloquent
{

    use SoftDeletingTrait;

    protected $fillable = ['offer_price', 'acceptance_status'];

    protected $dates = ['expires_at'];

    // Special case - keep the rules in a static to allow access externally
    // without instantiating the class, populate $this->rules from constructor
    public static $static_rules = ['offer_price' => ['required', 'numeric']];
    protected $rules = [];

    // Def class constants and a container to reference the acceptance status
    const OFFER_PENDING = 00;
    const OFFER_DECLINED = 10;
    const OFFER_DECLINED_AUTO = 11;
    const OFFER_ACCEPTED = 20;
    const OFFER_SELLER_CANCELLED = 30;
    public static $acceptance_statuses = [
        self::OFFER_PENDING => 'Pending',
        self::OFFER_DECLINED => 'Declined',
        self::OFFER_DECLINED_AUTO => 'Declined',
        self::OFFER_ACCEPTED => 'Accepted',
        self::OFFER_SELLER_CANCELLED => 'Cancelled by seller',
    ];

    ///////////////
    // Bootstrap //
    ///////////////


    public function __construct()
    {
        parent::__construct();

        // Set up rules
        $this->rules = self::$static_rules;
    }


    /**
     * Boot the parent, register observer
     */
    public static function boot()
    {
        parent::boot();

        Offer::observe(new OfferObserver);
    }


    ///////////////////
    // Relationships //
    ///////////////////


    /**
     * BelongsTo relationship with source advert
     *
     * @return Advert
     */
    public function advert()
    {
        return $this->belongsTo('Advert');
    }


    /**
     * BelongsTo relationship with potentially buying user
     *
     * @return User
     */
    public function initiator()
    {
        return $this->belongsTo('User', 'initiator_id');
    }


    ///////////////
    // Accessors //
    ///////////////


    /**
     * Virtual property for display of offer acceptance status
     *
     * @return string
     */
    public function getAcceptanceStatusStringAttribute()
    {
        return self::$acceptance_statuses[$this->acceptance_status];
    }


    /**
     * Get a GBP formatted currency string for the offer price
     *
     * @return String
     */
    public function getGbpOfferPriceStringAttribute()
    {
        return Converter::to('currency.gbp')->value($this->offer_price)->format();
    }


    ////////////
    // Scopes //
    ////////////


    /**
     * Limit query to only pending (not expired, declined or auto declined).
     * NOTE: extra where closure for query grouping
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopePending($query)
    {
        return $query->where(function($query) {
            $query->where('expires_at', '>=', Carbon::now())
            ->where('acceptance_status', '=', self::OFFER_PENDING);
        });
    }


    /**
     * Limit query to only accepted offers with outstanding payment
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopePaymentRequired($query)
    {
        return $query->where(function($query) {
            $query->where('acceptance_status', '=', self::OFFER_ACCEPTED)
            ->whereHas('advert', function($query) {
                $query->whereNull('purchased_at');
            });
        });
    }


    /**
     * Limit query to only accepted offers which have been paid for
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopePaymentComplete($query)
    {
        return $query->where(function($query) {
            $query->where('acceptance_status', '=', self::OFFER_ACCEPTED)
            ->whereHas('advert', function($query) {
                $query->whereNotNull('purchased_at');
            });
        });
    }


    /**
     * Limit query to only actioned (expired or not on pending status)
     * NOTE: extra where closure for query grouping
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopeActioned($query)
    {
        return $query->where(function($query) {
            $query->where('expires_at', '<', Carbon::now())
            ->orWhere('acceptance_status', '!=', self::OFFER_PENDING);
        });
    }


    /**
     * Scope to limit results for use in Ajax partials
     *
     * @param Query $query
     * @return Query
     */
    public function scopeForAjax($query)
    {
        return $query->orderBy('created_at', 'DESC')->limit(10);
    }
}

src/app/controllers/Admin/MembersController.php
<?php

namespace Admin;

// Domain
use User;
use Role;

// Core
use Input;
use Redirect;
use View;

// Third Party
use Notification;

class MembersController extends \BaseController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $users = User::all();
        return View::make('admin.members.index', compact('users'));
    }


    /**
     * Make admin
     *
     * @param  User   $user
     * @return Response
     */
    public function promote(User $user)
    {
        $user->setBaseRole(Role::ROLE_ADMIN);
        Notification::success('Role changed');
        return Redirect::route('admin.members.index');
    }


    /**
     * Make standard member
     *
     * @param  User   $user
     * @return Response
     */
    public function demote(User $user)
    {
        $user->setBaseRole(Role::ROLE_MEMBER);
        Notification::success('Role changed');
        return Redirect::route('admin.members.index');
    }


    /**
     * Deactivate (remove all base roles)
     *
     * @param  User   $user
     * @return Response
     */
    public function deactivate(User $user)
    {
        $user->deactivate();
        Notification::success('User deactivated');
        return Redirect::route('admin.members.index');
    }
}

src/app/views/member/listings/_fields.blade.php
{{ Former::populate($advert) }}

{{ Former::text('title') }}
{{ Former::textarea('body')->rows(10) }}

{{ Former::text('price')->pattern('[-+]?[0-9]*[.,]?[0-9]+')->placeholder('&pound;') }}

<?php $reserve_tooltip_markup = <<<HTML
<abbr title="Any offers made below this value will be declined automatically, though you will still be able to see the declined offers in your dashboard. This value is never displayed to potential buyers.">
	Reserve Price
</abbr>
HTML;
?>

{{ Former::text('min_offer_price', $reserve_tooltip_markup) ->pattern('[-+]?[0-9]*[.,]?[0-9]+')->placeholder('&pound;') }}

{{ Former::select('category_id', 'Category')->options($categories)->placeholder('Please select')->addClass('hierarchy not-select2') }}
{{ Former::select('manufacturer_id', 'Manufacturer')->options($manufacturers)->placeholder('Please select') }}

<span id="mfr_other_freetext_container">
	{{ Former::text('mfr_other_freetext', ' ')->placeholder('Enter manufacturer here') }}
</span>

{{ Former::actions(
	Button::primary('Save')->submit(),
	Button::danger('Cancel')->asLinkTo(route('member.listings.index'))
) }}

src/app/views/member/listings/_form.blade.php
@extends('member.layout')

@section('content')

<div class="row">

	<div class="col-md-12 col-lg-12">

		<div class="panel panel-default">

		@yield('main')

		</div> {{-- /.panel-primary --}}
	</div> {{-- /.col-* --}}
</div> {{-- /.row --}}

@stop

src/app/views/member/listings/_galleryitem.blade.php
{{-- Partial used to render a gallery item --}}

<div data-id="{{ $photo->id }}" class="sortable-item gallery-item well well-sm clearfix">
	
	<div class="row">

		<div class="col-xs-8">

			<p>Uploaded: <span class="text-muted">{{ $photo->image_updated_at->diffForHumans() }}</span></p>
			{{ Form::open(['url' => route('member.listings.gallery.destroy', [$advert->id, $photo->id]), 'method' => 'DELETE']) }}
			    <button type="submit" class="btn btn-xs btn-danger gallery-delete">
			    	<span class="glyphicon glyphicon-remove"></span>Delete this file
			    </button>
			{{ Form::close() }}

		</div>

		<div class="col-xs-4">

			<img src="{{ $photo->image->url('thumb') }}" class="img-responsive pull-right">

		</div>

	</div>

</div>

src/app/views/member/listings/_table.blade.php
<table class="table table-striped data-table" id="admin-adverts-index">

	<thead>
		<tr>
			<th class="table-widget-fixed-column" data-orderable="false">{{-- Controls --}}</th>
			<th>{{-- Title --}}</th>
			<th data-orderable="false">{{-- Approval status --}}</th>
			<th>Price</th>
			<th>Offers</th>
			<th>Sale Status</th>
		</tr>
	</thead>

	<tbody>
	@foreach ($adverts as $advert)
		<tr>
			<td>

				{{-- Manage dropdown --}}
				<div class="btn-group">
					<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false" aria-label="Manage Item">
						<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
					</button>
					<ul class="dropdown-menu" role="menu">

						{{-- Always show these options --}}
						<li>
							{{ Form::open(array('route' => array('member.listings.summary', $advert->id), 'method' => 'GET')) }}
							    <button type="submit" class="btn btn-link">All Offers</button>
							{{ Form::close() }}
						</li>

						{{-- Only show edit options if advert is not yet purchased --}}
						@if ($advert->purchase_status == Advert::ADVERT_AVAILABLE)
							<li>
								{{ Form::open(array('route' => array('member.listings.interstitial', $advert->id), 'method' => 'GET')) }}
								    <button type="submit" class="btn btn-link">Edit</button>
								{{ Form::close() }}
							</li>

							<li>
								{{ Form::open(array('route' => array('member.listings.destroy', $advert->id), 'method' => 'DELETE')) }}
								    <button type="submit" class="btn btn-link">Delete</button>
								{{ Form::close() }}
							</li>
						@endif

						{{-- Only show 'mark shipped' option is purchase is complete --}}
						@if ($advert->purchase_status == Advert::ADVERT_PURCHASED)
							<li>
								{{ Form::open(array('route' => array('member.listings.shipped', $advert->id), 'method' => 'POST')) }}
								    <button type="submit" class="btn btn-link">Mark as Shipped</button>
								{{ Form::close() }}
							</li>
						@endif

						{{-- Only show 'cancel sale' option if item is reserved but not paid for --}}
						@if ($advert->purchase_status == Advert::ADVERT_RESERVED)
							<li>
								{{ Form::open(array('route' => array('member.listings.cancel_sale', $advert->id), 'method' => 'POST')) }}
								    <button type="submit" class="btn btn-link">Cancel Offer and Re-list</button>
								{{ Form::close() }}
							</li>
						@endif											

					</ul>
				</div> {{--- ./Manage dropdown --}}

			</td>

			<td>
				@if ($advert->purchase_status == Advert::ADVERT_AVAILABLE && $advert->approval_status == Advert::ADVERT_APPROVED)
					{{ link_to_route('public.advert', $advert->title, ['slug' => $advert->slug], ['target' => '_blank']) }}
				@else 
					{{ link_to_route('public.advert.archived', $advert->title, ['slug' => $advert->slug], ['target' => '_blank']) }}
				@endif
			</td>

			<td>
				<?php $label_colour = $advert->approval_status == Advert::ADVERT_APPROVED ? 'primary' : 'warning' ?>
				<span class="label label-{{ $label_colour }}">{{ $advert->approval_status_string }}</span>
			</td>

			<td>{{ $advert->gbp_price_string }}</td>

			<td>
				@if (! $advert->offers()->pending()->get()->isEmpty())
					{{ link_to_route('member.listings.summary', 
						$advert->offers()->pending()->get()->count() . ' offers', 
						['id' => $advert->id]) 
					}}
				@endif
			</td>
			
			<td>
				@if ($advert->purchase_status == Advert::ADVERT_AVAILABLE)
					{{ $advert->purchase_status_string }}
				@else
					{{ link_to_route('member.listings.summary', $advert->purchase_status_string,
						['id' => $advert->id]) 
					}}
				@endif
			</td>
			
		</tr>
	@endforeach
	</tbody>
</table>

src/app/views/member/listings/active.blade.php
@extends('member.layout')

@section('content')

<div class="row">

	<div class="col-md-12 col-lg-12">

		<div class="panel panel-default">

			<div class="panel-heading">
				<h1>Active Listings</h1>
				<a class="btn btn-default" href="{{ route('member.listings.create') }}" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Advert</a>
			</div>

			<div class="panel-body">

				@if ($adverts->isEmpty())

					<div class="well">
						<p>You haven't listed any items for sale at the moment. Why not 
						{{ link_to_route('member.listings.create', 'list one right now?') }}
						</p>
					</div>

				@else

					@include('member.listings._table', compact('adverts'))

				@endif

			</div> {{-- /.panel-body --}}
		</div> {{-- /.panel-primary --}}
	</div> {{-- /.col-* --}}
</div> {{-- /.row --}}

@stop

src/app/views/member/listings/create.blade.php
@extends('member.listings._form')

@section('title', "Adding a new listing")

@section('main')

<div class="panel-heading">
	<h1>Add Listing</h1>
</div>

<div class="panel-body">

	{{ Former::open(route('member.listings.store'))->method('POST') }}

		@include('member.listings._fields')

	{{ Former::close() }}

</div> {{-- /.panel-body --}}

@stop

src/app/views/member/listings/edit.blade.php
@extends('member.listings._form')

@section('title', "Editing {$advert->title}")

@section('main')

<div class="panel-heading">
	<h1>Edit Listing</h1>
	<p class="text-info">Please note that once saved, your advert may be temporarily 
	unavailable while we approve your updates.</p>
	<p class="text-info">Editing your listing's <b>price</b> or <b>minimum offer price</b>
	will not return it to draft status, so feel free to amend these whenever you need to.</p>
</div>

<div class="panel-body">

	{{ Former::open(route('member.listings.update', $advert->id))->method('PUT') }}

		@include('member.listings._fields')

	{{ Former::close() }}

</div> {{-- /.panel-body --}}

@stop

src/app/views/member/listings/summary.blade.php
@extends('member.layout')

@section('title', "Summary for {$advert->title}")

@section('content')

<div class="row">

	<div class="col-md-12 col-lg-12">

		<div class="panel panel-default">

			<div class="panel-heading">
				<h2>{{ $advert->title }}</h2>
				<p>Added {{ $advert->created_at->diffForHumans() }}</p>
			</div>

			<div class="panel-body">

				<div class="row">

					{{-- Show winner/purchase details if appropriate --}}
					@unless ($advert->winning_offer === false)

						<div class="col-xs-12">

							<h2>Purchaser</h2>

							<div class="alert alert-success">

								<p class="lead">
									{{ link_to_route('messages.create', "Message buyer", $advert->winning_offer->initiator->username, 
										['class' => 'btn btn-xs btn-info pull-right']) 
									}}
									This advert was purchased for 
									{{ $advert->winning_offer->gbp_offer_price_string }}
									by <strong>{{ $advert->winning_offer->initiator->username }}</strong>
									@if ($advert->winning_offer->initiator->profile->full_name)
										({{ $advert->winning_offer->initiator->profile->full_name }})
									@endif
									@if ($advert->winning_offer->initiator->profile->telephone_country)
										from {{ $advert->winning_offer->initiator->profile->country->country_name }}
									@endif
									{{ $advert->winning_offer->created_at->diffForHumans() }}
								</p>

							</div>

							<h2>PayPal</h2>

							@if ($advert->winning_transaction)

								<div class="alert alert-success">

									<p class="lead">
										@if (! $advert->shipped_at)

											{{ link_to_route('member.listings.shipped', 'Mark shipped', [$advert->id],
												['class' => 'btn btn-xs btn-info pull-right'])
											}}

										@endif
										The item was paid for 
										{{ $advert->winning_transaction->updated_at->diffForHumans() }}
										from PayPal ID
										{{ $advert->winning_transaction->paypal_sender_email }}
									</p>

								</div>

							@else

								<div class="alert alert-danger">

									<p class="lead">
										The item has not yet been paid for, so do not ship until payment 
										has been received in your PayPal account!
									</p>

								</div>

							@endif


							@if ($advert->shipped_at)

								<h2>Shipping</h2>

								<div class="alert alert-success">

									<p class="lead">It was marked as shipped
										{{ $advert->shipped_at->diffForHumans() }}
									</p>

								</div>

							@endif

						</div>

					@endunless

					<div class="col-sm-6">

						<h3>Pending offers</h3>
						@if ($advert->offers()->pending()->count())

							<div class="alert alert-info">
								@foreach ($advert->offers()->pending()->get() as $offer)
									<p>
										<strong>{{ $offer->gbp_offer_price_string }}</strong>
										from <span class="text-muted">{{ $offer->initiator->username }}</span>
									</p>

									{{-- Accept and decline --}}
									{{ link_to_route('member.offers.accept', 'Accept', [$offer->id], ['class' => 'btn btn-xs btn-success']) }}
									{{ link_to_route('member.offers.decline', 'Decline', [$offer->id], ['class' => 'btn btn-xs btn-danger']) }}

								@endforeach
							</div>
						
						@else

							<div class="alert alert-warning" role="alert">
								<p>None</p>
							</div>
						
						@endif

					</div>

					<div class="col-sm-6">
						<h3>Actioned offers</h3>

						@if ($advert->offers()->actioned()->count())

							<div class="alert alert-info">
								@foreach ($advert->offers()->actioned()->get() as $offer)
									<p>
										<strong>{{ $offer->gbp_offer_price_string }}</strong>
										from <span class="text-muted">{{ $offer->initiator->username }}</span>,
										<span class="text-success">{{ $offer->acceptance_status_string }}</span>
									</p>
								@endforeach
							</div>

						@else

							<div class="alert alert-warning" role="alert">
								<p>None</p>
							</div>

						@endif

					</div>


				</div> {{-- ./row --}}

				<div class="text-center">
					{{ link_to_route('member.dashboard', 'Return to dashboard', 
						null, ['class' => 'btn btn-primary'])
					}}
				</div>

			</div> {{-- /.panel-body --}}
		</div> {{-- /.panel-default --}}
	</div> {{-- /.col-* --}}
</div> {{-- /.row --}}

@stop