src/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// Routes are split into seperate files - get them here
foreach (File::allFiles(__DIR__ . '/routes') as $files) {

    require_once $files->getPathName();

}

src/app/models/Activity.php
<?php

class Activity extends Eloquent
{
    use SoftDeletingTrait;

    protected $fillable = ['title', 'body'];


    ///////////////////
    // Relationships //
    ///////////////////
    

    /**
     * Define belongsTo relationship with user
     *
     * @return Collection
     */
    public function user()
    {
        return $this->belongsTo('User');
    }


    /**
     * Define belongsTo relationship with role
     *
     * @return Collection
     */
    public function role()
    {
        return $this->belongsTo('Role');
    }


    ///////////////
    // Accessors //
    ///////////////


    /**
     * Get a short, tagless version of the body content
     *
     * @return string
     */
    public function getBodySummaryAttribute()
    {
        return substr(strip_tags($this->body), 0, 100);
    }


    ////////////
    // Scopes //
    ////////////


    /**
     * Filter results to only activities owned by current user
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopeOwnedBySelf($query)
    {
        if (Confide::user()) {
            return $query->where('user_id', '=', Confide::user()->id);
        } else {
            // If not logged in ensure the scope returns nothing
            return $query->whereNull('id');
        }
    }


    /**
     * Filter to include unread only
     *
     * @param  Builder $query
     * @return Builder
     */
    public function scopeUnread($query)
    {
        return $query->whereNull('read');
    }
}

src/app/controllers/Admin/ActivitiesController.php
<?php

namespace Admin;

// Domain
use Activity;
use Role;

// Core
use Input;
use Redirect;
use View;

// Third Party
use Notification;
use Confide;

class ActivitiesController extends \BaseController
{

    /**
     * Display a listing of the resource.
     * GET /tags
     *
     * @return Response
     */
    public function index()
    {
        $activities = Role::where('name', '=', Role::ROLE_ADMIN)->firstOrFail()->activities;
        return View::make('admin.activities.index', compact('activities'));
    }


    /**
     * Mark as read - called via ajax
     *
     * @param  Activity $activity
     * @return Response
     */
    public function markRead(Activity $activity)
    {
        $activity->read = true;
        $activity->save();
        return Response::json('Marked as read', 200);
    }


    /**
     * Update the resource (simply toggle read/unread status)
     *
     * @param  Activity $activity
     * @return Response
     */
    public function update(Activity $activity)
    {
        $activity->read = $activity->read ? false : true;
        $activity->save();
        Notification::success('Activity read status toggled!');
        return Redirect::route('admin.activities.index');
    }


    /**
     * Update all resources for this role (simply mark them as read)
     *
     * @return Response
     */
    public function updateAll()
    {
        Role::where('name', '=', Role::ROLE_ADMIN)->firstOrFail()->activities()
            ->update(['read' => true]);
        Notification::success('Marked all activities as read!');
        return Redirect::route('admin.activities.index');
    }


    /**
     * Delete the resource
     *
     * @param  Activity $activity
     * @return Response
     */
    public function destroy(Activity $activity)
    {
        $activity->delete();
        Notification::success('Activity deleted!');
        return Redirect::route('admin.activities.index');
    }


    /**
     * Delete all resources for this user
     *
     * @return Response
     */
    public function destroyAll()
    {
        Role::where('name', '=', Role::ROLE_ADMIN)->firstOrFail()->activities()
            ->delete();
        Notification::success('All activities deleted');
        return Redirect::route('admin.activities.index');
    }
}

src/app/controllers/Member/ActivitiesController.php
<?php

namespace Member;

// Domain
use Activity;
use Role;

// Core
use Input;
use Redirect;
use View;
use Response;

// Third Party
use Notification;
use Confide;

class ActivitiesController extends \BaseController
{

    /**
     * Display a listing of the resource.
     * GET /tags
     *
     * @return Response
     */
    public function index()
    {
        $activities = Confide::user()->activities;
        return View::make('member.alerts', compact('activities'));
    }



    /**
     * Mark as read - called via ajax
     *
     * @param  Activity $activity
     * @return Response
     */
    public function markRead(Activity $activity)
    {
        $activity->read = true;
        $activity->save();
        return Response::json('Marked as read', 200);
    }


    /**
     * Update the resource (simply toggle read/unread status)
     *
     * @param  Activity $activity
     * @return Response
     */
    public function update(Activity $activity)
    {
        $activity->read = $activity->read ? false : true;
        $activity->save();
        Notification::success('Activity read status toggled!');
        return Redirect::route('member.alerts.index');
    }


    /**
     * Update all resources for this role (simply mark them as read)
     *
     * @return Response
     */
    public function updateAll()
    {
        Confide::user()->activities()->update(['read' => true]);
        Notification::success('Marked all activities as read!');
        return Redirect::route('member.alerts.index');
    }


    /**
     * Delete the resource
     *
     * @param  Activity $activity
     * @return Response
     */
    public function destroy(Activity $activity)
    {
        $activity->delete();
        Notification::success('Activity deleted!');
        return Redirect::route('member.alerts.index');
    }


    /**
     * Delete all resources for this user
     *
     * @return Response
     */
    public function destroyAll()
    {
        Confide::user()->activities()->delete();
        Notification::success('All activities deleted');
        return Redirect::route('member.alerts.index');
    }
}

src/app/views/admin/activities/index.blade.php
@extends('admin.layout')

@section('content')

<div class="row">

	<div class="col-md-12 col-lg-12">
		
		<h1>Alerts</h1>

		<div class="alert alert-info" role="alert">
			<p>This list provides an at-a-glace view of various alerts which may require your
			attention. This listing is shared by all admins, so actions you take here affect any other admins
			as well.</p>
		</div>

		<div class="panel panel-primary">

			<div class="panel-heading">
				<a class="btn btn-default" href="{{ route('admin.activities.update_all') }}" role="button"><span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span> Mark all as read</a>
				<a class="btn btn-default" href="{{ route('admin.activities.delete_all') }}" role="button"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete all</a>

			</div>

			<div class="panel-body">

				@if ($activities->isEmpty())

					<div class="alert alert-warning" role="alert">
						<p>No alerts found. Once read, alerts are removed after one month.</p>
					</div>

				@else 

					<table class="table table-striped data-table-plain" id="admin-activities-index">

						<thead>
							<tr>
								<th>{{-- Read status --}}</th>
								<th>{{-- Controls --}}</th>
								<th>{{-- Added --}}</th>
								<th>{{-- Title --}}</th>
								<th>{{-- Body --}}</th>
							</tr>
						</thead>

						<tbody>

						@foreach ($activities as $activity)
						
							<tr>

								<td>
									{{-- Read/unread marks --}}
									@if (!$activity->read)
										<?php $glyphicon = 'glyphicon-certificate' ?>
									@else
										<?php $glyphicon = 'glyphicon-ok-circle' ?>
									@endif
									<span class="glyphicon {{ $glyphicon }}" aria-hidden="true"></span>
								</td>

								<td>
									{{-- Manage dropdown --}}
									<div class="btn-group">
										<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false" aria-label="Manage Item">
											<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
										</button>
										<ul class="dropdown-menu" role="menu">
											<li>
												{{ Form::open(array('route' => array('admin.activities.update', $activity->id), 'method' => 'PATCH')) }}
												    <button type="submit" class="btn btn-link">Toggle read/unread</button>
												{{ Form::close() }}
											</li>
											<li>
												{{ Form::open(array('route' => array('admin.activities.destroy', $activity->id), 'method' => 'DELETE')) }}
												    <button type="submit" class="btn btn-link">Delete</button>
												{{ Form::close() }}
											</li>
										</ul>
									</div> {{--- ./Manage dropdown --}}
								</td>

								{{-- Output the rest of the line data --}}
								<td>{{ $activity->created_at->diffForHumans() }}</td>
								<td><strong>{{ $activity->title }}</strong></td>
								<td>
									{{-- Show body summary and a link to pass to bootbox.js --}}
									{{ $activity->body_summary }}&hellip;
									<a href="#" class="bootbox-alerts-popup" data-message="{{{ $activity->body }}}"
									data-read-url="{{ route('member.activities.mark_read', ['id' => $activity->id]) }}">View more</a>
								</td>

							</tr>

						@endforeach

						</tbody>
					</table>

				@endif

			</div> {{-- /.panel-body --}}
		</div> {{-- /.panel-primary --}}
	</div> {{-- /.col-* --}}
</div> {{-- /.row --}}

@stop